/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_ctimer.h"
#include "fsl_clock.h"
#include "fsl_gpio.h"
#include "fsl_port.h"
#include "fsl_lpspi.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for NCN_InitPeripherals functional group */
/* Definition of peripheral ID */
#define TIMEBASE_PERIPHERAL CTIMER4
/* Timer tick frequency in Hz (input frequency of the timer) */
#define TIMEBASE_TICK_FREQ 1000000UL
/* Timer tick period in ns (input period of the timer) */
#define TIMEBASE_TICK_PERIOD 1000UL
/* Definition of PWM period channel. */
#define TIMEBASE_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of channel 0 ID */
#define TIMEBASE_MATCH_0_CHANNEL kCTIMER_Match_0
/* TimeBase interrupt vector ID (number). */
#define TIMEBASE_TIMER_IRQN CTIMER4_IRQn
/* Alias for GPIO0 peripheral */
#define NCN_IRQ_INTERRUPT_GPIO GPIO0
/* Alias for PORT0 */
#define NCN_IRQ_INTERRUPT_PORT PORT0
/* NCN_IRQ_Interrupt interrupt vector ID (number). */
#define NCN_IRQ_INTERRUPT_INT_0_IRQN GPIO00_IRQn
/* NCN_IRQ_Interrupt interrupt vector priority. */
#define NCN_IRQ_INTERRUPT_INT_0_IRQ_PRIORITY 3
/* NCN_IRQ_Interrupt interrupt handler identifier. */
#define NCN_IRQ_Handler GPIO00_IRQHandler
/* Definition of peripheral ID */
#define NCN_SPI_PERIPHERAL ((LPSPI_Type *)LP_FLEXCOMM0)
/* Definition of clock source frequency */
#define NCN_SPI_CLOCK_FREQ 24000000UL

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const ctimer_config_t TimeBase_config;
extern const ctimer_match_config_t TimeBase_Match_0_config;
extern const lpspi_master_config_t NCN_SPI_config;

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
  /* Single callback function declaration */
extern void NCN_Timebase_Callback(uint32_t flags);
extern ctimer_callback_t TimeBase_callback[];

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

void NCN_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
